
export const CHALLENGES = {
  en: [
    "Dance for 30 seconds to the song chosen by the person on your right.",
    "Imitate someone in the group for one minute.",
    "Walk like a zombie for 20 seconds.",
    "Sing in English for 10 seconds.",
    "Do 10 squats.",
    "Say the alphabet backwards.",
    "Tell a joke.",
    "Act as if you just won an award.",
    "Imitate an animal.",
    "Speak with a weird accent for 1 minute.",
    "Strike an exaggerated pose and take a photo.",
    "Say 3 good things about the person on your right.",
    "Walk like a runway model.",
    "Do 5 push-ups.",
    "Invent a word and its meaning in one minute.",
    "Dance like a robot.",
    "Hold a plank for 30 seconds.",
    "Eat something given by the person on your right with your eyes closed.",
    "Reveal your hidden talent (make it up).",
    "Imitate a famous laugh.",
    "Speak for 1 minute without using the letter A.",
    "Everyone must lightly hit you with a pillow.",
    "Sing like an opera singer.",
    "Act as if you are in slow motion.",
    "Tell a funny story.",
    "Balance on one foot for 20 seconds.",
    "Say a tongue twister fast.",
    "Dance exaggerated reggaeton.",
    "Imitate a crying baby.",
    "Say 2 things you dislike about someone in the room.",
    "Make a weird sound and repeat it 5 times.",
    "Act like a street vendor.",
    "Walk like a penguin.",
    "Say a fun fact.",
    "Create an improvised choreography.",
    "Imitate a teacher.",
    "Spin around 10 times quickly.",
    "Make an ugly face for 10 seconds.",
    "Speak like a radio host.",
    "Clap only when someone looks at you for one minute.",
    "Mime a sport.",
    "Say 5 things you like.",
    "Dance salsa for 20 seconds.",
    "Imitate a famous character.",
    "Freeze like a statue until someone moves.",
    "Sing a children's song.",
    "Walk like the floor is burning.",
    "Give a wholesome compliment to someone in the group.",
    "Act like a superhero.",
    "Create an invented greeting.",
    "Say a word in another language.",
    "Dance like you are in a disco.",
    "Count to 10 without moving your lips.",
    "Imitate a drunk person.",
    "Do a yoga pose.",
    "Tell an obvious lie.",
    "Act like you are famous.",
    "Have a staring contest with someone.",
    "Walk backwards for 10 steps.",
    "Dance using only your arms.",
    "Do a runway-style walk.",
    "Imitate an animal sound and let others guess.",
    "Act like you just won the lottery.",
    "Dance with a chair.",
    "Say 3 things you would do if you were invisible.",
    "Walk like an elderly person.",
    "Act like you are in a soap opera.",
    "Do an evil laugh.",
    "Say a proverb.",
    "Imitate an angry person.",
    "Strike a victory pose.",
    "Say something positive about the group.",
    "Walk like a giant.",
    "Take a funny group selfie.",
    "Dance like a rag doll.",
    "Act like an adult or a child.",
    "Say your favorite food and defend it.",
    "Do a fake interview with someone.",
    "Imitate a famous greeting.",
    "Dance without moving your feet.",
    "Act like you are in a commercial.",
    "Say a weird wish.",
    "Have a funny face competition.",
    "Imitate an Arabic dance.",
    "Walk like you are wearing high heels.",
    "Hold a frozen pose for 10 seconds.",
    "Give a sincere compliment.",
    "Act like a villain.",
    "Perform a short free act.",
    "Create a ridiculous rule for the game.",
    "Dance like you just won a battle.",
    "Mime a profession.",
    "Say something that embarrasses you.",
    "EVERYONE: the floor is lava (last one on the floor loses).",
    "Strike an anime-style pose.",
    "Imitate a cartoon sound.",
    "Say an exaggerated “thank you”.",
    "Everyone dances together for 10 seconds.",
    "Hold your breath for 15 seconds.",
    "Do a ridiculous dance for 20 seconds."
  ],

  es: [
    "Baila 30 segundos la canción que diga la persona a tu derecha.",
    "Imita a alguien del grupo por un minuto.",
    "Camina como zombie por 20 segundos.",
    "Canta en inglés por 10 segundos.",
    "Haz 10 sentadillas.",
    "Di el abecedario al revés.",
    "Cuenta un chiste.",
    "Actúa como si ganaras un premio.",
    "Imita a un animal.",
    "Habla con un acento raro por 1 minuto.",
    "Haz una pose exagerada y toma una foto.",
    "Di 3 cosas buenas de la persona a tu derecha.",
    "Camina como modelo en una pasarela.",
    "Haz 5 flexiones.",
    "Inventa una palabra y su significado en un minuto.",
    "Baila como robot.",
    "Haz plancha por 30 segundos.",
    "Come algo que te dé la persona a tu derecha con los ojos cerrados.",
    "Di tu talento oculto (invéntalo).",
    "Imita una risa famosa.",
    "Habla sin usar la letra A por 1 minuto.",
    "Todos deben darte con una almohada.",
    "Canta como ópera.",
    "Actúa como si estuvieras en cámara lenta.",
    "Cuenta una anécdota graciosa.",
    "Haz equilibrio en un pie por 20 segundos.",
    "Di un trabalenguas rápido.",
    "Baila reguetón exagerado.",
    "Imita a un bebé llorando.",
    "Di 2 cosas que te desagraden de alguien de la sala.",
    "Haz un sonido extraño y repítelo 5 veces.",
    "Actúa como vendedor ambulante.",
    "Camina como pingüino.",
    "Di un dato curioso.",
    "Haz una coreografía improvisada.",
    "Imita a un profesor.",
    "Da 10 vueltas rápido.",
    "Haz una cara fea por 10 segundos.",
    "Habla como locutor de radio.",
    "Aplaude solo cuando alguien te mire por un minuto.",
    "Haz mímica de un deporte.",
    "Di 5 cosas que te gusten.",
    "Baila salsa por 20 segundos.",
    "Imita a un personaje famoso.",
    "Haz una estatua hasta que alguien se mueva.",
    "Canta una canción infantil.",
    "Camina como si el piso quemara.",
    "Di un cumplido sano a alguien del grupo.",
    "Actúa como superhéroe.",
    "Haz un saludo inventado.",
    "Di una palabra en otro idioma.",
    "Baila como si estuvieras en una disco.",
    "Cuenta hasta 10 sin mover los labios.",
    "Imita a un borracho.",
    "Haz una pose de yoga.",
    "Di una mentira obvia.",
    "Actúa como si fueras famoso.",
    "Haz un reto de miradas con alguien.",
    "Camina hacia atrás 10 pasos.",
    "Baila solo con los brazos.",
    "Haz una presentación tipo pasarela.",
    "Imita un sonido de animal y que los demás adivinen.",
    "Actúa como si ganaras la lotería.",
    "Baila con una silla.",
    "Di 3 cosas que harías si fueras invisible.",
    "Camina como anciano.",
    "Actúa como si estuvieras en una telenovela.",
    "Haz una risa malvada.",
    "Di un refrán.",
    "Imita a alguien enojado.",
    "Haz una pose de victoria.",
    "Di algo positivo del grupo.",
    "Camina como si fueras gigante.",
    "Haz una selfie grupal graciosa.",
    "Baila como muñeco de trapo.",
    "Actúa como si fueras un adulto o un niño.",
    "Di tu comida favorita y defiéndela.",
    "Haz una entrevista falsa a alguien.",
    "Imita un saludo famoso.",
    "Baila sin mover los pies.",
    "Actúa como si estuvieras en un comercial.",
    "Di un deseo raro.",
    "Haz una competencia de caras raras.",
    "Imita un baile árabe.",
    "Camina como si llevaras tacones.",
    "Haz una pose congelada por 10 segundos.",
    "Di un cumplido sincero.",
    "Actúa como villano.",
    "Haz una mini actuación libre.",
    "Di una regla absurda para el juego.",
    "Baila como si ganaras una batalla.",
    "Haz una mímica de una profesión.",
    "Di algo que te dé vergüenza.",
    "TODOS: el piso es lava (se saca al último en el suelo).",
    "Haz una pose estilo anime.",
    "Imita un sonido de caricatura.",
    "Di un “gracias” exagerado.",
    "Baila todos juntos por 10 segundos.",
    "Aguanta la respiración 15 segundos.",
    "Haz un baile ridículo durante 20 segundos."
  ],

  fr: [
    "Danse pendant 30 secondes sur une chanson choisie par la personne à ta droite.",
    "Imite quelqu’un du groupe pendant une minute.",
    "Marche comme un zombie pendant 20 secondes.",
    "Chante en anglais pendant 10 secondes.",
    "Fais 10 squats.",
    "Récite l’alphabet à l’envers.",
    "Raconte une blague.",
    "Agis comme si tu venais de gagner un prix.",
    "Imite un animal.",
    "Parle avec un accent bizarre pendant une minute.",
    "Prends une pose exagérée et prends une photo.",
    "Dis trois choses positives sur la personne à ta droite.",
    "Marche comme un mannequin sur un podium.",
    "Fais 5 pompes.",
    "Invente un mot et explique sa signification en une minute.",
    "Danse comme un robot.",
    "Fais la planche pendant 30 secondes.",
    "Mange quelque chose donné par la personne à ta droite les yeux fermés.",
    "Révèle ton talent caché (invente-le).",
    "Imite un rire célèbre.",
    "Parle pendant une minute sans utiliser la lettre A.",
    "Tout le monde te frappe avec un coussin.",
    "Chante comme un chanteur d’opéra.",
    "Agis comme si tu étais au ralenti.",
    "Raconte une anecdote drôle.",
    "Tiens-toi en équilibre sur un pied pendant 20 secondes.",
    "Dis un virelangue rapidement.",
    "Danse du reggaeton de manière exagérée.",
    "Imite un bébé qui pleure.",
    "Dis deux choses que tu n’aimes pas chez quelqu’un dans la pièce.",
    "Fais un bruit étrange et répète-le cinq fois.",
    "Agis comme un vendeur ambulant.",
    "Marche comme un pingouin.",
    "Dis un fait amusant.",
    "Crée une chorégraphie improvisée.",
    "Imite un professeur.",
    "Tourne sur toi-même 10 fois rapidement.",
    "Fais une grimace pendant 10 secondes.",
    "Parle comme un animateur radio.",
    "Applaudis seulement quand quelqu’un te regarde pendant une minute.",
    "Mime un sport.",
    "Dis cinq choses que tu aimes.",
    "Danse la salsa pendant 20 secondes.",
    "Imite un personnage célèbre.",
    "Reste immobile comme une statue jusqu’à ce que quelqu’un bouge.",
    "Chante une chanson pour enfants.",
    "Marche comme si le sol était en lave.",
    "Fais un compliment sain à quelqu’un du groupe.",
    "Agis comme un super-héros.",
    "Invente une salutation.",
    "Dis un mot dans une autre langue.",
    "Danse comme si tu étais en boîte de nuit.",
    "Compte jusqu’à 10 sans bouger les lèvres.",
    "Imite une personne ivre.",
    "Fais une pose de yoga.",
    "Dis un mensonge évident.",
    "Agis comme si tu étais célèbre.",
    "Fais un concours de regard avec quelqu’un.",
    "Marche en arrière pendant 10 pas.",
    "Danse uniquement avec les bras.",
    "Fais une présentation façon défilé.",
    "Imite le son d’un animal et fais-le deviner.",
    "Agis comme si tu avais gagné à la loterie.",
    "Danse avec une chaise.",
    "Dis trois choses que tu ferais si tu étais invisible.",
    "Marche comme une personne âgée.",
    "Agis comme dans une telenovela.",
    "Fais un rire diabolique.",
    "Dis un proverbe.",
    "Imite quelqu’un de fâché.",
    "Prends une pose de victoire.",
    "Dis quelque chose de positif sur le groupe.",
    "Marche comme un géant.",
    "Prends un selfie de groupe drôle.",
    "Danse comme une poupée de chiffon.",
    "Agis comme un adulte ou comme un enfant.",
    "Dis ton plat préféré et défends-le.",
    "Fais une fausse interview avec quelqu’un.",
    "Imite une salutation célèbre.",
    "Danse sans bouger les pieds.",
    "Agis comme si tu étais dans une publicité.",
    "Dis un souhait étrange.",
    "Fais un concours de grimaces.",
    "Imite une danse arabe.",
    "Marche comme si tu portais des talons.",
    "Reste figé dans une pose pendant 10 secondes.",
    "Fais un compliment sincère.",
    "Agis comme un méchant.",
    "Fais une mini performance libre.",
    "Invente une règle absurde pour le jeu.",
    "Danse comme si tu avais gagné une bataille.",
    "Mime un métier.",
    "Dis quelque chose qui te gêne.",
    "TOUT LE MONDE : le sol est en lave (le dernier debout perd).",
    "Prends une pose style anime.",
    "Imite un son de dessin animé.",
    "Dis un “merci” exagéré.",
    "Tout le monde danse ensemble pendant 10 secondes.",
    "Retiens ta respiration pendant 15 secondes.",
    "Fais une danse ridicule pendant 20 secondes."
  ]
};

export const TRUTHS = {
  en: [
    "Confess a weird habit.",
    "Say something embarrassing.",
    "Confess a small lie you told.",
    "Say something you always forget.",
    "Confess a silly fear.",
    "Say a weird habit you have.",
    "Confess something you did and nobody noticed.",
    "Say something that makes you nervous.",
    "Confess something you're not good at.",
    "Say something that really annoys you.",
    "... add the remaining 90 here in the same format ..."
  ],
  es: [
    "Confiesa una manía rara que tengas.",
    "Di algo que te dé vergüenza admitir.",
    "Confiesa una mentira pequeña que hayas dicho.",
    "Di algo que siempre se te olvida.",
    "Confiesa un miedo tonto.",
    "Di una costumbre rara que tengas.",
    "Confiesa algo que hiciste y nadie lo notó.",
    "Di algo que te pone nervioso.",
    "Confiesa algo que no se te da bien.",
    "Di una cosa que te molesta mucho.",
    "... add the remaining 90 here in the same format ..."
  ],
  fr: [
    "Avoue une manie bizarre que tu as.",
    "Dis quelque chose que tu as honte d’admettre.",
    "Avoue un petit mensonge que tu as déjà dit.",
    "Dis quelque chose que tu oublies toujours.",
    "Avoue une peur ridicule.",
    "Dis une habitude étrange que tu as.",
    "Avoue quelque chose que tu as fait et que personne n’a remarqué.",
    "Dis quelque chose qui te rend nerveux.",
    "Avoue quelque chose dans lequel tu n’es pas bon.",
    "Dis quelque chose qui t’énerve vraiment.",
    "... add the remaining 90 here in the same format ..."
  ]
};
